GAUSSIAN_KERNEL_SIZE_PAPER = 301
GAUSSIAN_CUTOFF_FREQ_PAPER = 30

HYPOECHOIC_LOW_BOUNDARY = 20

FIND_SEED_POINT_STOPPING_CRITERION = 2
FIND_SEED_POINT_MAXIMUM_ITERATIONS = 100
FIND_SEED_POINT_NUMBER_DIRECTIONS = 12
FIND_SEED_POINT_RADIUS = 12
