import numpy as np
from enum import Enum

FOCUS_HASH_LABEL = 'FOCUS'
FRAME_LABEL = 'FRAME'

class HSV_COLOR_THRESHOLD(Enum):
    LOWER = [60, 50, 50]
    UPPER = [100, 255, 255]

class HSV_GRAYSCALE_THRESHOLD(Enum):
    LOWER = [1, 1, 1]
    UPPER = [255, 255, 255]

class IMAGE_TYPE(Enum):
    GRAYSCALE = 'GRAYSCALE'
    COLOR = 'COLOR'

class READOUT_ABBREVS(Enum):
    COLOR_MODE = 'COLOR_MODE'
    COLOR_TYPE = 'COLOR_TYPE'
    RADIALITY = 'RADIALITY'
    RAD = 'RAD'
    ARAD = 'ARAD'
    COLOR_LEVEL = 'COL'
    CPA = 'CPA'
    WALL_FILTER = 'WF'
    PULSE_REPITITION_FREQUENCY = 'PRF'
    SIZE = 'SIZE'

TUMOR_TYPES = ['BENIGN', 'MALIGNANT']
TUMOR_TYPE_LABEL = 'TUMOR_TYPE'

WALL_FILTER_MODES = ['LOW', 'MED', 'HIGH']